name: remote ssh command
on: [push]
env:
  FIRST_NAME : Arun
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Run Deploy Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: sh scripts/test.sh $FIRST_NAME
       
