name: CI Script
on: [push]
env:
  USER: ${{secrets.SSH_USER}}
  HOST: ${{secrets.SSH_HOST_IP}}

jobs:
  deploy:
    runs-on: ubuntu-18.04 
    steps:   
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: $ { { secrets.SSH_PRIVATE_KEY } }
        known_hosts: $ { { secrets.KNOW_HOST } }

    - name: Run Script
      run: ssh $USER@$HOST bash /home/$USER/scripts/redeploy-proshanti-lms.sh
     
