name: Deploy


on:
  push:
    branches: [ master ]

jobs:
  build: 
    -name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
    uses: shimataro/ssh-key-action@v2
    with:
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      known_hosts : 'just-a-string-to-ignore-error'
    - name: Adding known host
    run: ssh-keyscan -H ${{ secrets.SSH_HOST_IP }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
    run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_IP }}:/home/proshanti/scripts/redeploy-proshanti-lms.sh


