name: CI Script
on: [push]
env:
  USER: ${{secrets.SSH_USER}}
  HOST: ${{secrets.SSH_HOST_IP}}

jobs:
  deploy:
    runs-on: ubuntu-18.04 
    steps:   
    - name: Intialize SSH
      uses: garygrossgarten/github-action-ssh@release
      with:
    host: $HOST
    username: $USER
    passphrase: 'ignore-error'
    privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
     command: ls 
     
