name: CI Script
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-18.04 
    steps:   
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: $ { { secrets.SSH_PRIVATE_KEY } }
        known_hosts: $ { { secrets.SSH_HOST_IP } }

    - name: Execute test Script
      run: ssh proshanti@${{ secrets.SSH_HOST_IP}} bash ping.sh