name: CI/CD
on:
  push:
    branches: [ master ]

jobs:
  deploy_to_dev:
    name: Deployment to Dev Environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        KEY : ${{ secrets.SSLCOMMERZ_INTEGRATION_KEY }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "$KEY"

    - name: SSH and run deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: sh scripts/tesh.sh
