name: CI/CD
on:
  push:
    branches: [ master ]

jobs:
  deploy_to_dev:
    - name: SSH and run deploy script
      env:
        NAME: "LOCAL"
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: NAME
        script: sh scripts/test.sh $NAME
