name: CI/CD
on:
  push:
    branches: [ master ]

jobs:
  deploy_to_dev:
    name: Deployment to Dev Environment
    runs-on: ubuntu-latest
    steps:
    - name: SSH and run deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          set -e
          cd /home/proshanti/frappe-bench
          ls -a

