name: Testing
on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  testing_project:
    name: Implement testing
    runs-on: ubuntu-latest
    steps:
      - run: echo "now this not works as pr is opned"