name: Testing
on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  testing_project:
    name: Implement testing
    runs-on: ubuntu-latest
    steps:
      - run: echo "only running this job on pull request only one time  to master branch"