name: Testing
on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.run_id }}
  cancel-in-progress: true

jobs:
  testing_project:
    name: Implement testing
    runs-on: ubuntu-latest
    steps:
      - run: echo "hope this run not again"